done 1 sprint 1 step
arigatory/react-burger pull request #3
Opened 2022-05-05 02:48 UTC by arigatory

2022-05-05 05:49 UTC, andryxxa93 requested changes
Вы отлично справились! Видно, что с контекстом вы разобрались и используете его верно. 

Но есть несколько моментов, которые можно исправить:
1) SelectedBunContext излишен. Булку можно помещать в SelectedIngredientsContext. 
2) Избавиться от автоматического вызова заказа при монтировании Burderconstructor.

Можно улучшить:
1) Абстрактные названия типа `data` и т.п. лучше не использовать. Называйте переменные конкретнее, это сделает код более понятным.
2) Когда из функции или массива достается какой-то ненужный элемент его принято обозначать нижним подчеркиванием `_`
3) Не оборачивать в контекст компоненты, которые в нем не нуждаются.
4) Использовать вместо `<br/>` стили 
5) Сделать рефактор renderedItems
6) Вынести вызов к api и константу с адресом в отдельный файл
7) Убрать лишние конструкции `try catch`
8) Убрать `console.log` 

На данном этапе вы можете не исправлять замечания помеченные как "Можно исправить", но на следующем они станут обязательными к исправлению.

Замечания помеченные как "Можно улучшить" к исправлению не обязательны, но они помогут сделать код чище и избежать ошибок в будущем.

В pull request вы найдете комментарии с более развернутым описанием проблемы и возможными путями её решения.

Удачных правок!

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/app/App.jsx
> +import { SelectedBunContext } from '../../services/selectedBunContext';
Можно исправить:
SelectedBunContext излишен. Булку можно помещать в SelectedIngredientsContext.

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/app/App.jsx
>  	const data = useIngredients();
Можно улучшить: 
Абстрактные названия типа `data` лучше не использовать. Называйте переменные конкретнее, это сделает код более понятным.

2022-05-05 05:49 UTC, andryxxa93 commented on src/hooks/useOrder.js
> +    const url = 'https://norma.nomoreparties.space/api/orders';
Можно улучшить:
Сейчас у вас дублируется константа с api. Если в будущем адрес изменится, его придется менять во всех местах. Это не очень удобно. Вызовы к api можно вынести в отдельный файл и там завести константу `const BURGER_API_URL = "https://norma.nomoreparties.space/api";`. Потом можно будет просто добавлять конкретный endpoint - ``` fetch(`${BURGER_API_URL}/ingredients`) ```

2022-05-05 05:49 UTC, andryxxa93 commented on src/hooks/useOrder.js
> +            console.log(e);
Можно улучшить: 
Выводы в консоль нужны только для разработки, так что лучше их убирать перед сдачей работы. Это лишний side effect, который не несет никакой пользы для пользователя сайтом.

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
> +		setOrder(makeOrder());
Можно исправить: 
1) Сейчас у вас заказ происходит сразу при монтировании компонента BurgerConstructor. Заказ должен проихсодить только после нажатия кнопки "Оформить заказ". Дело всё в том, что хук useOrder() срабатывает сразу при монтировании. Постарайтесь это исправить и заодно упростить сам хук, если оставите его, там возвращение функции вместо переменной не обязательно.

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
>  		renderedItems = selectedIngredients.map((item, index) => {
Можно улучшить: 
Лучше вместо пустой строки когда список ингредиентов пуст записывать null, тогда React не будет ничего рендерить. https://ru.react.js.org/docs/conditional-rendering.html#%D0%9F%D1%80%D0%B5%D0%B4%D0%BE%D1%82%D0%B2%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BE%D1%82%D1%80%D0%B8%D1%81%D0%BE%D0%B2%D0%BA%D0%B8-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
>  			return (
Можно исправить:
Создавать отступы желательно с помощью стилей, но не тегов br. Стили более управляемы и их легко поменять.  
```
<br />
  <ul>{renderedItems}</ul>
<br />
```

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/app/App.jsx
> +				const [ i, setI ] = selectedIngredientsState;
Можно улучшить:
Когда из функции или массива достается какой-то ненужный элемент его принято обозначать нижним подчеркиванием `_`

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/app/App.jsx
> +						<div className={styles.container}>
Можно улучшить:
Header не нуждается в данных контекста, поэтому оборачивать его в них нет необходимости.

2022-05-05 05:49 UTC, andryxxa93 commented on src/components/burger-constructor/burger-constructor.jsx
>  	let renderedItems;
Можно улучшить: 
Можно использовать функцию для рендера ингредиентов `renderItems,` чтобы не создавать отдельную переменную `renderedItems`. И обернуть её в useMemo или useEffect, чтобы избежать лишних операций.

2022-05-05 05:49 UTC, andryxxa93 commented on src/hooks/useOrder.js
> +            }
Можно улучшить: 
конструкция `try catch` тут лишняя, так как `getData` уже использует её внутри себя.

2022-05-16 16:33 UTC, arigatory commented on src/components/app/App.jsx
> +import { SelectedBunContext } from '../../services/selectedBunContext';
не понимаю, чем так лучше, логика приложения сложнее станет, разве нет?

2022-05-16 21:06 UTC, arigatory commented on src/components/burger-constructor/burger-constructor.jsx
> +		setOrder(makeOrder());
смог только частично исправить, не совсем понятно как лушче сделать, нужно сам хук менять?

2022-05-17 15:30 UTC, andryxxa93 approved these changes
Ваша работа принята! 

Удачного продолжения обучения!

2022-05-17 16:45 UTC, merged